fix #301
facebook/metro pull request #749
Opened 2021-12-17 18:11 UTC by mfbx9da4

**Summary**

**Test plan**

2022-01-03 20:02 UTC, rh389 requested changes

2022-01-08 19:11 UTC, mfbx9da4 commented on packages/metro-minify-terser/src/minifier.js
> +        : config.sourceMap
Yeah great point. Updated now, let me know if that works! 🙂

2022-01-17 10:53 UTC, rh389 approved these changes

2022-01-17 10:57 UTC, mfbx9da4 commented
Glad to see it's been approved. Would you like me to squash my commits or will you do that when you merge via github's `Squash & Merge` feature?

2022-01-17 12:05 UTC, rh389 commented
Hi @mfbx9da4 - the process is a little bit idiosyncratic because the source of truth here is another repo within Meta, mirrored to GitHub. 

I fixed up that whitespace internally and the system is going through the process of landing the (squashed) commit now - a bot will let us know here when it does.

2022-01-17 12:09 UTC, closed without merging